<?php

return array(
    'config' => '系統配置',
    'ecmall_integrate_guide' => 'ECMall 整合向導',
    'welcome_integrate_ecmall' => '您好，歡迎使用 ECMall 整合程序',
    'have_missing_item' => '您忘了填寫以下項目',
    'ucenter_info' => '請填寫 UCenter 的相關信息',
    'uc_connect' => 'UCenter 連接方式',
    'uc_api' => 'UCenter 的 URL',
    'uc_ip' => 'UCenter 的 IP',
    'uc_password' => 'UCenter 創始人密碼',
    'app_name' => 'ECMall 網站名稱',
    'app_url' => 'ECMall 訪問地址',
    'uc_api_error' => 'UCenter 的 URL 輸入有誤，必須以 http:// 開頭',
    'app_url_error' => 'ECMall 訪問地址輸入有誤，必須以 http:// 開頭',
    'dns_error' => 'UCenter URL域名解析失敗，請手動設置UCenter的IP',
    'get_ucinfo_failed' => '獲取用戶中心信息數據失敗，請返回檢查',
    'charset_error' => 'ECMall 字符集（%s）和 UCenter 字符集（%s）不同，請選擇正確的版本重新安裝 ECMall 或 UCenter',
    'version_error' => '您的 UCenter 服務端版本（%s）與客戶端版本（%s）不一致，請下載正確的客戶端版本重新整合',
    'app_exists' => 'UCenter 只能整合一個 ECMall，如果需要重新整合，請您登錄 UCenter 管理中心應用管理將 ECMall 應用刪除後再進行整合',
    'password_error' => 'UCenter 創始人密碼錯誤，請重新填寫',
    'connect_error' => 'UCenter 通信失敗，請檢查 UCenter URL地址是否能正常訪問',
    'uc_db_error' => 'UCenter數據庫連接失敗，您可以嘗試選擇Http方式連接',
    'finish' => '完成',
    'integrate_successed'          => '恭喜您！整合UCenter成功！感謝您使用ECMall，請在下面選擇您的去向',
    'config_title'          => 'UCenter整合程序',
    'config_desc'          => '支持 ucenter1.0 和 1.5 版本',
    'finish_title'          => 'UCenter整合完成',
    'finish_desc'          => '',
    'close_window' => '關閉',
    'frontend' => '商城首頁',
    'backend' => '商城後台',
    'install_first'  => '請先安裝ECMall',
    'password_inconsistent'  => '兩次輸入的密碼不一致',
    'email_error'  => 'EMail格式錯誤',
    'apptagtemplates'  => array(
        'goods_name'   =>    '商品名稱',
        'uid'  => '用戶ID',
        'username'  => '用戶名',
        'dateline'  => '日期',
        'url'  => 'URL地址',
        'image'  => '圖片',
        'goods_price'  => '商品價格',
    ),
    'user_not_exists'  => '用戶不存在，請檢查您的輸入，您可以嘗試使用新的用戶',
    'admin_password_error'  => '您輸入的用戶密碼有誤，請檢查',
    'unknow_error'  => '未知錯誤',
    'invalid_user_name'  => '不合法的用戶名',
    'blocked_usre_name'  => '該用戶名包含不允許注冊的詞語，無法使用',
    'user_exists'  => '用戶已存在，請更換一個',
    'blocked_email'  => '該EMail已被禁止注冊，請更換',
    'email_exists'  => '該EMail已被注冊',
    'exists_user'  => '使用 ucenter 現有的用戶',
    'new_user'  => '使用新用戶',
    'user_name'  => '管理員用戶名',
    'email'  => '管理員EMail',
    'password'  => '管理員密碼',
    'password_confirm'  => '密碼確認',
    'mall_admin_info'   => '請填寫整合後 ECMall 的管理員信息',
    'mall_admin_info_desc' => '',
    'integrate_locked' => '整合程序已鎖定，如果您想重新運行整合程序，請刪除 data/integrate.lock 文件。',
    'uc_client_not_exist' => 'uc_client 目錄不存在或文件不完整，請檢查後再運行整合程序。',
    'attension' => '請注意',
    'attension_content' => '整合後，ECMall 中現有的用戶、店鋪及相關信息都將被刪除，請確認後再往下執行。',
    'please_read_warning' => '請確認您是否已經知道整合後將引起的後果，若您是初裝用戶，可以忽略',
);

?>
